{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bugsnag",
    "module": "bugsnag-android-ndk",
    "version": "5.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-android-core",
          "version": {
            "requires": "5.28.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-plugin-android-anr",
          "version": {
            "requires": "5.28.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-plugin-android-ndk",
          "version": {
            "requires": "5.28.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugsnag-android-ndk-5.28.1.aar",
          "url": "bugsnag-android-ndk-5.28.1.aar",
          "size": 717,
          "sha512": "5253f4882f2c9fce6c4430582bd1f7593b672d70dc728bc4ea07327e07f8750c28822420df43e71d4587a9313a741b0d45a86093a13a7dda9c64ecaaa7046df8",
          "sha256": "64b18693c070f807e23c5435bc452d9e5bc3f21487c2ef6198ae26826d5953a2",
          "sha1": "3b97610fcdfefda1adb7b92bc433ceddcf23e338",
          "md5": "06211a53e28c402fffad0ba774cfb54a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-android-core",
          "version": {
            "requires": "5.28.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-plugin-android-anr",
          "version": {
            "requires": "5.28.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag-plugin-android-ndk",
          "version": {
            "requires": "5.28.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugsnag-android-ndk-5.28.1.aar",
          "url": "bugsnag-android-ndk-5.28.1.aar",
          "size": 717,
          "sha512": "5253f4882f2c9fce6c4430582bd1f7593b672d70dc728bc4ea07327e07f8750c28822420df43e71d4587a9313a741b0d45a86093a13a7dda9c64ecaaa7046df8",
          "sha256": "64b18693c070f807e23c5435bc452d9e5bc3f21487c2ef6198ae26826d5953a2",
          "sha1": "3b97610fcdfefda1adb7b92bc433ceddcf23e338",
          "md5": "06211a53e28c402fffad0ba774cfb54a"
        }
      ]
    }
  ]
}
